/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param photo 
 * @param birthDate 
 * @param familyId 
 */
data class CreateFamilyMember (
    var firstName: kotlin.String,
    var lastName: kotlin.String,
    var email: kotlin.String,
    val photo: kotlin.String? = null,
    var birthDate: java.time.LocalDate? = null,
    val familyId: kotlin.Long? = null
) {

}

