/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param price 
 * @param product 
 * @param amount 
 * @param shoppingListId 
 */
data class CreateShoppingListItem (
    val price: kotlin.Int? = null,
    val product: kotlin.String? = null,
    val amount: kotlin.Int? = null,
    val shoppingListId: kotlin.Long? = null
) {

}

