/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param birthDate 
 * @param email 
 * @param familyId 
 * @param firstName 
 * @param id 
 * @param lastName 
 * @param photo 
 * @param uid 
 * @param username 
 */
data class FamilyMemberPlain (
    val email: kotlin.String,
    val firstName: kotlin.String,
    val id: kotlin.Long,
    val lastName: kotlin.String,
    val uid: kotlin.String,
    val birthDate: java.time.LocalDateTime? = null,
    val familyId: kotlin.Long? = null,
    val photo: kotlin.String? = null,
    val username: kotlin.String? = null
) {

}

