/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.FamilyPlain

/**
 * 
 * @param birthDate 
 * @param email 
 * @param family 
 * @param firstName 
 * @param id 
 * @param lastName 
 * @param photo 
 * @param uid 
 * @param username 
 */
data class FamilyMemberGet (
    val email: kotlin.String,
    val firstName: kotlin.String,
    val id: kotlin.Long,
    val lastName: kotlin.String,
    val uid: kotlin.String,
    val birthDate: java.time.LocalDate? = null,
    val family: FamilyPlain? = null,
    val photo: kotlin.String? = null,
    val username: kotlin.String? = null
) {

}

