/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param uid 
 * @param username 
 * @param password 
 */
data class RegistrationDTO (
    val uid: kotlin.String,
    val username: kotlin.String,
    val password: kotlin.String
)

