/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param birthDate 
 * @param email 
 * @param familyId 
 * @param lastName 
 * @param photo 
 * @param surname 
 * @param uid 
 */
data class CreateFamilyMember (
    val email: kotlin.String,
    val lastName: kotlin.String,
    val surname: kotlin.String,
    val uid: kotlin.String,
    val birthDate: java.time.LocalDateTime? = null,
    val familyId: kotlin.Long? = null,
    val photo: kotlin.String? = null
) {

}

