/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.FamilyMemberPlain

/**
 * 
 * @param code 
 * @param head 
 * @param id 
 * @param members 
 * @param name 
 */
data class FamilyPlain (
    val code: kotlin.String,
    val id: kotlin.Long,
    val name: kotlin.String,
    val head: FamilyMemberPlain? = null,
    val members: kotlin.Array<FamilyMemberPlain>? = null
) {

}

