/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param accessToken 
 * @param refreshToken 
 */
data class Tokens (
    val accessToken: kotlin.String,
    val refreshToken: kotlin.String
) {

}

